# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sqrl' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  # Pods for Sqrl

  # target 'Sqrl-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # target 'SqrlTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

target 'Sqrl-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sqrl-tvOS

  target 'Sqrl-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end



end
