# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Sqrl' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native', subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'BatchedBridge'
    ]


  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'

  # Pods for Sqrl

  # target 'Sqrl-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # target 'SqrlTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end

    if target.name == "React"
      target.remove_from_project
    end
  end
end

target 'Sqrl-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sqrl-tvOS

  target 'Sqrl-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end



end
